### ISSUE TITLE
how to make tests run

### ISSUE THREAD

**Issue by bob-junior** [raydium-io/raydium-cpi-example#9]
When I click run button of rustRover,  it failed.

![image](https://github.com/user-attachments/assets/e40d18d5-dd8a-461e-a527-46d45d6166f3)

/Users/pc/.nvm/versions/node/v23.3.0/bin/node /Users/pc/RustroverProjects/raydium-cpi-example/cpmm-cpi/node_modules/mocha/bin/mocha --ui bdd --reporter /Applications/RustRover.app/Contents/plugins/nodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js /Users/pc/RustroverProjects/raydium-cpi-example/cpmm-cpi/tests/initialize.test.ts --grep ^initialize test 

TypeError: Cannot read properties of undefined (reading 'async')
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:306:22)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1376:24)
    at Module._compile (node:internal/modules/cjs/loader:1528:5)
    at Object..js (node:internal/modules/cjs/loader:1698:10)
    at Module.load (node:internal/modules/cjs/loader:1303:32)
    at Function._load (node:internal/modules/cjs/loader:1117:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1325:12)
    at require (node:internal/modules/helpers:136:16)
    at exports.requireOrImport (/Users/pc/RustroverProjects/raydium-cpi-example/cpmm-cpi/node_modules/mocha/lib/nodejs/esm-utils.js:60:20)
    at async exports.loadFilesAsync (/Users/pc/RustroverProjects/raydium-cpi-example/cpmm-cpi/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at async singleRun (/Users/pc/RustroverProjects/raydium-cpi-example/cpmm-cpi/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async exports.handler (/Users/pc/RustroverProjects/raydium-cpi-example/cpmm-cpi/node_modules/mocha/lib/cli/run.js:374:5)

**Comment by 0x777A** [comment]
cd acpmm-cpi
yarn && anchor test
